version: '3.4'

services:
  geocintrunner:
    image: geocintrunner
    build:
      context: report
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: production
    ports:
      - 5000:5000