version: '3.4'

services:
  geocintrunner:
    image: statusreport
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: production
    ports:
      - 9000:5000
    volumes:
      - /home/gis/geocint/make_profile.db:/usr/src/app/make_profile.db